namespace LithoManager.Api.Contracts.Payroll;

public sealed record PayrollConceptResponse(
    int PayrollConceptId,
    string PayrollConceptCode,
    string Name,
    string? Description,
    string ConceptKind,
    bool IsSystemConcept,
    bool IsTaxableForIncomeTax,
    bool IsSubjectToSocialContributions,
    bool CountsForAguinaldo,
    bool IsActive,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record SocialContributionTypeResponse(
    int SocialContributionTypeId,
    string ContributionCode,
    string Name,
    string InstitutionName,
    string ContributionGroup,
    bool AppliesToEmployee,
    bool AppliesToEmployer,
    bool UsesMinimumBase,
    bool IsActive,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record SocialContributionRateResponse(
    int SocialContributionRateId,
    int SocialContributionTypeId,
    string ContributionCode,
    string ContributionName,
    string InstitutionName,
    string ContributionGroup,
    bool AppliesToEmployee,
    bool AppliesToEmployer,
    bool UsesMinimumBase,
    decimal EmployeeRate,
    decimal EmployerRate,
    DateTime EffectiveFromDate,
    DateTime? EffectiveToDate,
    string? LegalReference,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record SocialContributionMinimumBaseResponse(
    int SocialContributionMinimumBaseId,
    int SocialContributionTypeId,
    string ContributionCode,
    string ContributionName,
    string InstitutionName,
    string ContributionGroup,
    decimal MinimumBaseAmount,
    DateTime EffectiveFromDate,
    DateTime? EffectiveToDate,
    string? LegalReference,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record IncomeTaxBracketResponse(
    int IncomeTaxBracketId,
    int TaxYear,
    string Periodicity,
    decimal LowerBoundAmount,
    decimal? UpperBoundAmount,
    decimal TaxRate,
    DateTime EffectiveFromDate,
    DateTime? EffectiveToDate,
    string? LegalReference,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record IncomeTaxCreditResponse(
    int IncomeTaxCreditId,
    string CreditCode,
    string Name,
    int TaxYear,
    string Periodicity,
    decimal CreditAmount,
    DateTime EffectiveFromDate,
    DateTime? EffectiveToDate,
    string? LegalReference,
    bool IsActive,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record WorkShiftTypeResponse(
    int WorkShiftTypeId,
    string WorkShiftTypeCode,
    string Name,
    decimal MaxOrdinaryHoursPerDay,
    decimal MaxOrdinaryHoursPerWeek,
    decimal MaxTotalHoursPerDay,
    DateTime EffectiveFromDate,
    DateTime? EffectiveToDate,
    bool IsActive,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record OvertimeRuleResponse(
    int OvertimeRuleId,
    string OvertimeRuleCode,
    string Name,
    decimal HourMultiplier,
    bool CountsForAguinaldo,
    DateTime EffectiveFromDate,
    DateTime? EffectiveToDate,
    bool IsActive,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record DisabilityTypeResponse(
    int DisabilityTypeId,
    string DisabilityTypeCode,
    string Name,
    bool CountsAsSalaryForAguinaldo,
    bool RequiresSubsidyTracking,
    bool ReducesWorkedDays,
    bool IsActive,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);

public sealed record AguinaldoRuleResponse(
    int AguinaldoRuleId,
    string AguinaldoRuleCode,
    string Name,
    byte CalculationStartMonth,
    byte CalculationStartDay,
    byte CalculationEndMonth,
    byte CalculationEndDay,
    decimal Divisor,
    byte PaymentDueMonth,
    byte PaymentDueDay,
    bool IncludesOrdinarySalary,
    bool IncludesOvertime,
    bool IncludesSalaryInKind,
    bool ExcludesCommonIllnessSubsidy,
    bool IncludesMaternitySubsidy,
    DateTime EffectiveFromDate,
    DateTime? EffectiveToDate,
    bool IsActive,
    DateTime CreatedAtUtc,
    int? CreatedByUserId,
    DateTime? UpdatedAtUtc,
    int? UpdatedByUserId,
    string RowVersion);
