<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8e7a19a0-b803-4e57-af78-70efa9018a56</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LithoManager.Application\LithoManager.Application.csproj" />
    <ProjectReference Include="..\LithoManager.Infraestructure\LithoManager.Infraestructure.csproj" />
  </ItemGroup>

</Project>
